site_name: Lab Template
repo_url: https://github.com/wcp-public-team/lab-template
edit_uri: ''
nav:
  - Home: index.md
  - Lab Part 1: page1.md
  - Lab Part 2: page2.md
  - Lab Part 3: page3.md
theme: readthedocs
markdown_extensions:
  - admonition